# Do not use Kong Ingress Controller
ingressController:
  enabled: false

image:
  repository: kong/kong-gateway
  tag: "3.6.1.4"

# Mount the secret created earlier
secretVolumes:
#  - kong-cluster-cert-test
  - kong-cluster-cert

env:
  # data_plane nodes do not have a database
  role: data_plane
  database: "off"

  # Tell the data plane how to connect to the control plane
  cluster_control_plane: kong-control-plane-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-control-plane-kong-clustertelemetry.kong.svc.cluster.local:8006

  # Configure control plane / data plane authentication
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
#  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert-test/tls.crt
#  cluster_cert: /etc/secrets/kong-cluster-cert-test/tls.crt
#  cluster_cert_key: /etc/secrets/kong-cluster-cert-test/tls.key

# Enterprise functionality
enterprise:
  enabled: true
  license_secret: kong-enterprise-license

# The data plane handles proxy traffic only
proxy:
  enabled: true
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

# These roles are served by the kong-cp deployment
admin:
  enabled: false

manager:
  enabled: false